### ISSUE TITLE
Unsuccessful primary host transaction causing reservation failure 

### ISSUE THREAD

**Issue by MarinKx** [Travelport/uapi-book-microservice#1]
Hi,

upon making following request:

`<soap:Envelope
    xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/">
    <soap:Body>
        <ns3:AirCreateReservationReq
            xmlns="http://www.travelport.com/schema/common_v45_0"
            xmlns:ns2="http://www.travelport.com/schema/air_v45_0"
            xmlns:ns3="http://www.travelport.com/schema/universal_v45_0"
            xmlns:ns4="http://www.travelport.com/schema/rail_v45_0"
            xmlns:ns5="http://www.travelport.com/schema/cruise_v45_0"
            xmlns:ns6="http://www.travelport.com/schema/vehicle_v45_0"
            xmlns:ns7="http://www.travelport.com/schema/hotel_v45_0"
            xmlns:ns8="http://www.travelport.com/schema/passive_v45_0"
            xmlns:ns9="http://www.travelport.com/soa/common/security/SessionContext_v1" TargetBranch="P7075712">
            <BillingPointOfSaleInfo OriginApplication="UAPI"/>
            <BookingTraveler>
                <BookingTravelerName First="John" Last="Smith"/>
                <PhoneNumber Location="DEN" CountryCode="1" AreaCode="303" Number="1234567"/>
                <SSR Key="1" Type="DOCS" Status="HK" FreeText="////20APR85/M//SMITH/JOHN"/>
            </BookingTraveler>
            <FormOfPayment Key="PDz8y7xu4hGdeB/wYIhwmw==" Type="Cash"/>
            <ns2:AirPricingSolution Key="ULi+U7Q2BKAbOlFCAAAAA==">
                <ns2:AirSegment Group="0" Carrier="AA" FlightNumber="416" ClassOfService="K" Origin="DEN" Destination="LAX" DepartureTime="2019-03-06T19:59:00-07:00" ArrivalTime="2019-03-06T21:22:00-08:00" ProviderCode="1G" FlightTime="223" Key="ULi+U7Q2BKAeOlFCAAAAA=="/>
                <ns2:AirSegment Group="0" Carrier="AA" FlightNumber="416" ClassOfService="K" Origin="LAX" Destination="DEN" DepartureTime="2019-03-23T15:45:00-07:00" ArrivalTime="2019-03-23T18:59:00-06:00" ProviderCode="1G" FlightTime="214" Key="gULi+U7Q2BKAZOlFCAAAAA=="/>
                <ns2:AirPricingInfo Key="ULi+U7Q2BKAbOlFCAAAAA==" PricingMethod="Auto" Taxes="34.4">
                    <ns2:FareInfo Key="ULi+U7Q2BKAhOlFCAAAAA==" FareBasis="1QFLEX" PassengerTypeCode="ADT" Origin="DEN" Destination="LAX" EffectiveDate="2019-09-25"/>
                    <ns2:BookingInfo BookingCode="K" CabinClass="Economy" FareInfoRef="ULi+U7Q2BKAhOlFCAAAAA==" SegmentRef="ULi+U7Q2BKAeOlFCAAAAA=="/>
                    <ns2:PassengerType Code="ADT"/>
                </ns2:AirPricingInfo>
            </ns2:AirPricingSolution>
            <ActionStatus Type="ACTIVE" TicketDate="T*" ProviderCode="1G"/>
        </ns3:AirCreateReservationReq>
    </soap:Body>
</soap:Envelope> `

we get the following error response:

`<SOAP:Envelope
    xmlns:SOAP="http://schemas.xmlsoap.org/soap/envelope/">
    <SOAP:Body>
        <SOAP:Fault>
            <faultcode>Server.Business</faultcode>
            <faultstring>Unsuccessful primary host transaction causing reservation failure.</faultstring>
            <detail>
                <common_v45_0:ErrorInfo
                    xmlns:common_v45_0="http://www.travelport.com/schema/common_v45_0">
                    <common_v45_0:Code>3515</common_v45_0:Code>
                    <common_v45_0:Service>AIRSVC</common_v45_0:Service>
                    <common_v45_0:Type>Business</common_v45_0:Type>
                    <common_v45_0:Description>Unsuccessful primary host transaction causing reservation failure.</common_v45_0:Description>
                    <common_v45_0:TransactionId>67CB0DCC0A07643CB39E5A6E69DC0C12</common_v45_0:TransactionId>
                </common_v45_0:ErrorInfo>
            </detail>
        </SOAP:Fault>
    </SOAP:Body>
</SOAP:Envelope> `

What might be the problem here?

uAPI username is: uAPI8224660885-9ba7683b , you can see target branch in request.

Thanks!

**Comment by vivekjyotipramanik** [comment]
Hi MarinKx,

Please share the AirPriceReq and AirPriceRsp for this flow. Thanks.

**Comment by MarinKx** [comment]
Hi Vivekjyoti,

Thanks for a quick response:

I'm attaching whole flow, different flights, same error.

Price req:

`<soap:Envelope
	xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/">
	<soap:Body>
		<ns2:AirPriceReq
			xmlns="http://www.travelport.com/schema/common_v45_0"
			xmlns:ns2="http://www.travelport.com/schema/air_v45_0"
			xmlns:ns3="http://www.travelport.com/schema/rail_v45_0"
			xmlns:ns4="http://www.travelport.com/soa/common/security/SessionContext_v1" AuthorizedBy="user" TargetBranch="P7075712">
			<BillingPointOfSaleInfo OriginApplication="UAPI"/>
			<ns2:AirItinerary>
				<ns2:AirSegment Group="0" Carrier="OU" FlightNumber="410" ProviderCode="1G" Origin="ZAG" Destination="FRA" DepartureTime="2019-10-02T07:45:00.000+02:00" ArrivalTime="2019-10-02T09:15:00.000+02:00" Key="7QW2q17Q2BKAYEteAAAAAA=="/>
			</ns2:AirItinerary>
			<ns2:AirPricingModifiers PlatingCarrier="OU"/>
			<SearchPassenger Code="ADT" BookingTravelerRef="e95f26ff-8a25-4bbe-9ace-714928216ddd"/>
			<ns2:AirPricingCommand>
				<ns2:AirPricingModifiers PlatingCarrier="OU"/>
				<ns2:AirSegmentPricingModifiers AirSegmentRef="7QW2q17Q2BKAYEteAAAAAA==" BrandTier="null"/>
			</ns2:AirPricingCommand>
			<ns2:AirPricingCommand/>
		</ns2:AirPriceReq>
	</soap:Body>
</soap:Envelope>`

Price resp.:
`<SOAP:Envelope
	xmlns:SOAP="http://schemas.xmlsoap.org/soap/envelope/">
	<SOAP:Body>
		<air:AirPriceRsp
			xmlns:air="http://www.travelport.com/schema/air_v45_0"
			xmlns:common_v45_0="http://www.travelport.com/schema/common_v45_0" TransactionId="6CD0AA4B0A0764775EFB6207BFDE3151" ResponseTime="3963">
			<common_v45_0:ResponseMessage Code="710401" Type="Warning" ProviderCode="1G">Taxes returned at the FareInfo level are for informational purposes only, and may differ from those returned at the Itinerary/Passenger Type levels.</common_v45_0:ResponseMessage>
			<common_v45_0:ResponseMessage Code="4766" Type="Warning" ProviderCode="1G">BrandTier should be 1-9999. BrandTier has been ignored.</common_v45_0:ResponseMessage>
			<common_v45_0:ResponseMessage Code="4400" Type="Warning">No Merchandising optional services returned for Flight(s) [OU][410]</common_v45_0:ResponseMessage>
			<air:AirItinerary>
				<air:AirSegment Key="fxmOr13R2BKAqFuhAAAAAA==" Group="0" Carrier="OU" FlightNumber="410" ProviderCode="1G" Origin="ZAG" Destination="FRA" DepartureTime="2019-10-02T07:45:00.000+02:00" ArrivalTime="2019-10-02T09:15:00.000+02:00" FlightTime="90" TravelTime="90" Distance="457" ClassOfService="E" ChangeOfPlane="false" OptionalServicesIndicator="false" AvailabilitySource="L" PolledAvailabilityOption="O and D cache or polled status used with different local status" AvailabilityDisplayType="Fare Specific Fare Quote Unbooked">
					<air:CodeshareInfo OperatingCarrier="OU">CROATIA AIRLINES</air:CodeshareInfo>
					<air:FlightDetails Key="fxmOr13R2BKArFuhAAAAAA==" Origin="ZAG" Destination="FRA" DepartureTime="2019-10-02T07:45:00.000+02:00" ArrivalTime="2019-10-02T09:15:00.000+02:00" FlightTime="90" TravelTime="90" Distance="457"/>
				</air:AirSegment>
			</air:AirItinerary>
			<air:AirPriceResult>
				<air:AirPricingSolution Key="fxmOr13R2BKAsFuhAAAAAA==" TotalPrice="HRK796.00" BasePrice="EUR67.00" ApproximateTotalPrice="EUR107.99" ApproximateBasePrice="EUR67.56" EquivalentBasePrice="HRK498.00" Taxes="HRK298.00" Fees="HRK0.00" ApproximateTaxes="EUR40.43" QuoteDate="2019-09-26">
					<air:AirSegmentRef Key="fxmOr13R2BKAqFuhAAAAAA=="/>
					<air:AirPricingInfo Key="fxmOr13R2BKAuFuhAAAAAA==" TotalPrice="HRK796.00" BasePrice="EUR67.00" ApproximateTotalPrice="EUR107.99" ApproximateBasePrice="EUR67.56" EquivalentBasePrice="HRK498.00" ApproximateTaxes="EUR40.43" Taxes="HRK298.00" LatestTicketingTime="2019-09-28T23:59:00.000+02:00" PricingMethod="Guaranteed" IncludesVAT="false" ETicketability="Yes" ProviderCode="1G">
						<air:FareInfo Key="fxmOr13R2BKAyFuhAAAAAA==" FareBasis="EEASY1" PassengerTypeCode="ADT" Origin="ZAG" Destination="FRA" EffectiveDate="2019-09-26T11:04:00.000+02:00" DepartureDate="2019-10-02" Amount="HRK498.00" TaxAmount="HRK298.00">
							<common_v45_0:Endorsement Value="FLT/CNX/CHG RESTRICTED"/>
							<common_v45_0:Endorsement Value="CHECK FARE NOTE"/>
							<air:FareRuleKey FareInfoRef="fxmOr13R2BKAyFuhAAAAAA==" ProviderCode="1G">6UUVoSldxwjcDUjgiWvyD8bKj3F8T9EyxsqPcXxP0TLGyo9xfE/RMsuWFfXVd1OAly5qxZ3qLwOXLmrFneovA5cuasWd6i8Dly5qxZ3qLwOXLmrFneovA0Kj1kXHN6jZ4bHmxr88+l3zd/VTAJtvZQ5CJVVv53OpRJ9BjYIO3at+CeOefa9UvJOFkR/cjA+wRVJEb3tT5ryMsThABxVToBll6FxyIC6cYuAWfcH2w92IEQfz1U0L79VQHb6Cbn5stT3DtB9yq9Dqkp0FEw0raOCbZ1nsUQQBswKEGcaKpTesnwp2JFYGGouFsAExMoVlv4Xvb2u1Qx+/he9va7VDH7+F729rtUMfv4Xvb2u1Qx+/he9va7VDHzyxauAs+veBE308BFXsd7QPNqcmmS6r7B2WN4EjYakqGukA+/4zcfmMebIbzCCs1iZH1zpFft9m5W4bRuwrrPA=</air:FareRuleKey>
							<air:Brand Key="fxmOr13R2BKAyFuhAAAAAA==" BrandFound="false" UpSellBrandFound="false"/>
						</air:FareInfo>
						<air:BookingInfo BookingCode="E" CabinClass="Economy" FareInfoRef="fxmOr13R2BKAyFuhAAAAAA==" SegmentRef="fxmOr13R2BKAqFuhAAAAAA==" HostTokenRef="fxmOr13R2BKAtFuhAAAAAA=="/>
						<air:TaxInfo Category="HR" Amount="HRK214.00" Key="fxmOr13R2BKAvFuhAAAAAA=="/>
						<air:TaxInfo Category="MI" Amount="HRK10.00" Key="fxmOr13R2BKAwFuhAAAAAA=="/>
						<air:TaxInfo Category="YQ" Amount="HRK74.00" Key="fxmOr13R2BKAxFuhAAAAAA=="/>
						<air:FareCalc>ZAG OU FRA 75.33EEASY1 NUC75.33END ROE0.889355</air:FareCalc>
						<air:PassengerType Code="ADT"/>
						<air:BaggageAllowances>
							<air:BaggageAllowanceInfo TravelerType="ADT" Origin="ZAG" Destination="FRA" Carrier="OU">
								<air:URLInfo>
									<air:URL>VIEWTRIP.TRAVELPORT.COM/BAGGAGEPOLICY/OU</air:URL>
								</air:URLInfo>
								<air:TextInfo>
									<air:Text>0P</air:Text>
									<air:Text>BAGGAGE DISCOUNTS MAY APPLY BASED ON FREQUENT FLYER STATUS/ ONLINE CHECKIN/FORM OF PAYMENT/MILITARY/ETC.</air:Text>
								</air:TextInfo>
								<air:BagDetails ApplicableBags="1stChecked" BasePrice="HRK223.00" ApproximateBasePrice="EUR30.25" TotalPrice="HRK223.00" ApproximateTotalPrice="EUR30.25">
									<air:BaggageRestriction>
										<air:TextInfo>
											<air:Text>UPTO50LB/23KG AND UPTO62LI/158LCM</air:Text>
										</air:TextInfo>
									</air:BaggageRestriction>
								</air:BagDetails>
								<air:BagDetails ApplicableBags="2ndChecked" BasePrice="HRK558.00" ApproximateBasePrice="EUR75.70" TotalPrice="HRK558.00" ApproximateTotalPrice="EUR75.70">
									<air:BaggageRestriction>
										<air:TextInfo>
											<air:Text>UPTO50LB/23KG AND UPTO62LI/158LCM</air:Text>
										</air:TextInfo>
									</air:BaggageRestriction>
								</air:BagDetails>
							</air:BaggageAllowanceInfo>
							<air:CarryOnAllowanceInfo Origin="ZAG" Destination="FRA" Carrier="OU">
								<air:TextInfo>
									<air:Text>1P</air:Text>
								</air:TextInfo>
								<air:CarryOnDetails ApplicableCarryOnBags="1" BasePrice="HRK0.00" ApproximateBasePrice="EUR0.00" TotalPrice="HRK0.00" ApproximateTotalPrice="EUR0.00">
									<air:BaggageRestriction>
										<air:TextInfo>
											<air:Text>UPTO18LB/8KG AND UPTO45LI/115LCM</air:Text>
										</air:TextInfo>
									</air:BaggageRestriction>
								</air:CarryOnDetails>
							</air:CarryOnAllowanceInfo>
						</air:BaggageAllowances>
					</air:AirPricingInfo>
					<air:FareNote Key="fxmOr13R2BKA2FuhAAAAAA==">RATE USED IN EQU TOTAL IS BSR 1EUR - 7.44HRK</air:FareNote>
					<air:FareNote Key="fxmOr13R2BKA3FuhAAAAAA==">LAST DATE TO PURCHASE TICKET: 28SEP19 ZAG</air:FareNote>
					<air:FareNote Key="fxmOr13R2BKA4FuhAAAAAA==">FARE HAS A PLATING CARRIER RESTRICTION</air:FareNote>
					<air:FareNote Key="fxmOr13R2BKA5FuhAAAAAA==">E-TKT REQUIRED</air:FareNote>
					<air:FareNote Key="fxmOr13R2BKA6FuhAAAAAA==">TICKETING FEES MAY APPLY</air:FareNote>
					<common_v45_0:HostToken Key="fxmOr13R2BKAtFuhAAAAAA==">GFB10101ADT00  01EEASY1                                010001#GFB200010101NADTV30217OUY00400001996M#</common_v45_0:HostToken>
				</air:AirPricingSolution>
			</air:AirPriceResult>
		</air:AirPriceRsp>
	</SOAP:Body>
</SOAP:Envelope>`

Book req:

`<soap:Envelope
	xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/">
	<soap:Body>
		<ns3:AirCreateReservationReq
			xmlns="http://www.travelport.com/schema/common_v45_0"
			xmlns:ns2="http://www.travelport.com/schema/air_v45_0"
			xmlns:ns3="http://www.travelport.com/schema/universal_v45_0"
			xmlns:ns4="http://www.travelport.com/schema/rail_v45_0"
			xmlns:ns5="http://www.travelport.com/schema/cruise_v45_0"
			xmlns:ns6="http://www.travelport.com/schema/vehicle_v45_0"
			xmlns:ns7="http://www.travelport.com/schema/hotel_v45_0"
			xmlns:ns8="http://www.travelport.com/schema/passive_v45_0"
			xmlns:ns9="http://www.travelport.com/soa/common/security/SessionContext_v1" TargetBranch="P7075712">
			<BillingPointOfSaleInfo OriginApplication="UAPI"/>
			<BookingTraveler>
				<BookingTravelerName First="John" Last="Smith"/>
				<PhoneNumber Location="ZAG" CountryCode="385" AreaCode="1" Number="1234567"/>
				<SSR Key="1" Type="DOCS" Status="HK" FreeText="////20APR85/M//SMITH/JOHN"/>
			</BookingTraveler>
			<FormOfPayment Key="PDz8y7xu4hGdeB/wYIhwmw==" Type="Cash"/>
			<ns2:AirPricingSolution Key="fxmOr13R2BKAsFuhAAAAAA==">
				<ns2:AirSegment Group="0" Carrier="OU" FlightNumber="410" ClassOfService="E" Origin="ZAG" Destination="FRA" DepartureTime="2019-10-02T07:45:00.000+02:00" ArrivalTime="2019-10-02T09:15:00.000+02:00" ProviderCode="1G" FlightTime="130" Key="7QW2q17Q2BKAYEteAAAAAA=="/>
				<ns2:AirPricingInfo Key="fxmOr13R2BKAuFuhAAAAAA==" PricingMethod="Auto" Taxes="40.43">
					<ns2:FareInfo Key="7QW2q17Q2BKAyHteAAAAAA==" FareBasis="EEASY1" PassengerTypeCode="ADT" Origin="ZAG" Destination="FRA" EffectiveDate="2019-09-26"/>
					<ns2:BookingInfo BookingCode="E" CabinClass="Economy" FareInfoRef="7QW2q17Q2BKAyHteAAAAAA==" SegmentRef="7QW2q17Q2BKAYEteAAAAAA=="/>
					<ns2:PassengerType Code="ADT"/>
				</ns2:AirPricingInfo>
			</ns2:AirPricingSolution>
			<ActionStatus Type="ACTIVE" TicketDate="T*" ProviderCode="1G"/>
		</ns3:AirCreateReservationReq>
	</soap:Body>
</soap:Envelope>`

Book rsp:

`<SOAP:Envelope
	xmlns:SOAP="http://schemas.xmlsoap.org/soap/envelope/">
	<SOAP:Body>
		<SOAP:Fault>
			<faultcode>Server.Business</faultcode>
			<faultstring>Unsuccessful primary host transaction causing reservation failure.</faultstring>
			<detail>
				<common_v45_0:ErrorInfo
					xmlns:common_v45_0="http://www.travelport.com/schema/common_v45_0">
					<common_v45_0:Code>3515</common_v45_0:Code>
					<common_v45_0:Service>AIRSVC</common_v45_0:Service>
					<common_v45_0:Type>Business</common_v45_0:Type>
					<common_v45_0:Description>Unsuccessful primary host transaction causing reservation failure.</common_v45_0:Description>
					<common_v45_0:TransactionId>6CD8768D0A0764775EFB620779E18E4F</common_v45_0:TransactionId>
				</common_v45_0:ErrorInfo>
			</detail>
		</SOAP:Fault>
	</SOAP:Body>
</SOAP:Envelope>`

Thanks!

**Comment by vivekjyotipramanik** [comment]
Hi MarinKx,

In the AirPriceRsp, HostToken was returned and whenever a HostToken is returned in AirPriceRsp, you have to use the HostToken in AirCreateReservationReq, which you are not using in this AirCreateReservationReq. Please find below the link with sample flow with HostToken. Thanks.

https://support.travelport.com/webhelp/uapi/uapi.htm#SampleWeb/Individual_Sample_Pages/036-ACH_Air_LFS-AC_Connections.htm%3FTocPath%3DSamples%7CXML%2520Samples%2520%7CAir%2520Samples%7CAir%2520Samples%7CAir%2520Workflows%7CAirline%2520Content%2520Hub%2520(ACH)%2520Workflows%7CAir%2520Canada%7C_____2
